# Generated by Django 5.2.7 on 2025-10-24 12:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=10.0, help_text='Commission percentage taken on each successful order.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_verified', models.BooleanField(default=False, help_text='If enabled, the seller is approved by admins and can list products publicly.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seller Profile',
                'verbose_name_plural': 'Seller Profiles',
                'db_table': 'profiles_seller',
                'indexes': [models.Index(fields=['shop_name'], name='idx_seller_shop_name'), models.Index(fields=['is_verified'], name='idx_seller_verified')],
            },
        ),
    ]
