# Generated by Django 5.2.7 on 2025-12-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='location',
            field=models.CharField(choices=[('MARY WELAYATY', 'Mary welayaty'), ('LEBAP WELAYATY', 'Lebap welayaty'), ('DASHOGUZ WELAYATY', 'Dashoguz welayaty'), ('BALKAN WELAYATY', 'Balkan welayaty'), ('AHAL WELAYATY', 'Ahal welayaty'), ('ASHGABAT SHAHERI', 'Ashgabat shaheri')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='phone_number',
            field=models.CharField(default='', help_text='Seller contact phone number', max_length=32),
            preserve_default=False,
        ),
    ]
