# Generated by Django 5.2.7 on 2025-10-24 12:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="Optional label like 'Home', 'Office'", max_length=60)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=24, validators=[django.core.validators.RegexValidator('^[0-9+()\\-\\s]{6,24}$', 'Invalid phone format')])),
                ('line1', models.CharField(max_length=180, verbose_name='Address line 1')),
                ('line2', models.CharField(blank=True, max_length=180, verbose_name='Address line 2')),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, max_length=120, verbose_name='State/Region')),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(help_text="ISO 3166-1 alpha-2 country code (e.g., 'DE', 'TR', 'HU', 'US')", max_length=2)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'shipping_address',
                'ordering': ('-is_default', '-created_at'),
                'indexes': [models.Index(fields=['user', 'is_default'], name='idx_addr_user_default'), models.Index(fields=['country', 'postal_code'], name='idx_addr_country_postal')],
            },
        ),
    ]
